"""Constants for the Beretta Besmart Thermostat integration."""

DOMAIN = "besmart"
DEFAULT_NAME = "Besmart Thermostat"
DEFAULT_ROOM_NAME = "room"
THERMOSTAT_ID = "thermostatId"
WIFIBOX_ID = "wifiBoxId"
MQTT_BROKER_HOST = "brokerHost"
MQTT_BROKER_PORT = "brokerPort"
MQTT_BROKER_USERNAME = "brokerUsername"
MQTT_BROKER_PASSWORD = "brokerPassword"
ROOM_TEMPERATURE = "roomTemp"
ANTI_FROST_TEMPERATURE = "antiFrostTemperature"
ECONOMY_TEMPERATURE = "economyTemperature"
COMFORT_TEMPERATURE = "comfortTemperature"
OUTSIDE_TEMPERATURE = "outSideTemp"
MAX_SETPOINT = "maxSetPoint"
MIN_SETPOINT = "minSetPoint"
CURRENT_SETPOINT = "currentSetPoint"
CLIMATIC_CURVE = "climaticCurve"
CURRENT_HEATING_SETPOINT = "heatingSetPoint"
HEATING = "heating"
MODE = "mode"
WIFI_SIGNAL = "wifiSignal"    
